services:
  php:
    build: ./services/php/
    container_name: redcap-php
    pull_policy: ${PULL_POLICY:-always}
    environment:
      DATABASE_HOST: db
      DATABASE_USER: redcap
      DATABASE_DATABASE: redcap
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-redcap123}
      DATABASE_SALT: ${DATABASE_SALT:-e35399f8f5499516c4ae52dbcc473969c929754b65a30a75db547ec676f9fbcab8345396d6ba701d5cdf2421858be3bb99e9}
    volumes:
      - ./redcap/:/var/www/html/:z
      - ./php.ini:/usr/local/etc/php/conf.d/redcap.ini:z
      - ./msmtprc:/etc/msmtprc:z
      - ./edocs:/var/www/edocs:z
    depends_on:
      - db

  cron:
    build: ./services/php/
    container_name: redcap-cron
    pull_policy: ${PULL_POLICY:-always}
    environment:
      DATABASE_HOST: db
      DATABASE_USER: redcap
      DATABASE_DATABASE: redcap
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-redcap123}
      DATABASE_SALT: ${DATABASE_SALT:-e35399f8f5499516c4ae52dbcc473969c929754b65a30a75db547ec676f9fbcab8345396d6ba701d5cdf2421858be3bb99e9}
    volumes:
      - ./redcap/:/var/www/html/:z
      - ./php.ini:/usr/local/etc/php/conf.d/redcap.ini:z
      - ./msmtprc:/etc/msmtprc:z
      - ./edocs:/var/www/edocs:z
    depends_on:
      - php
    command:
      - "crond"
      - "-f"

  nginx:
    build: ./services/nginx
    pull_policy: ${PULL_POLICY:-always}
    container_name: redcap-nginx
    ports:
      - ${HTTP_PORT:-8080}:80
    volumes:
      - ./redcap/:/var/www/html/:z
    depends_on:
      - php

  db:
    image: docker.io/mariadb:11.8
    pull_policy: ${PULL_POLICY:-always}
    container_name: redcap-mysql
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_USER: redcap
      MARIADB_PASSWORD: ${DATABASE_PASSWORD:-redcap123}
      MARIADB_DATABASE: redcap
    command:
      - --max_allowed_packet=1G
      - --optimizer_switch=rowid_filter=OFF
      - --query_cache_size=16777216
      - --query_cache_limit=16777216
      - --query_cache_type=1
      - --innodb_buffer_pool_size=2G
      - --innodb_buffer_pool_instances=8
      - --max_connections=400
      - --innodb_flush_log_at_trx_commit=2
      - --sync_binlog=0
      - --max_heap_table_size=8M
      - --tmp_table_size=8M

volumes:
  mysql:
